name: Testing on Ubuntu
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.2
          - 3.3
          - 3.4
        os:
          - ubuntu-latest
    name: Ruby ${{ matrix.ruby }} unit testing on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: unit testing
      env:
        CI: true
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake spec
